"""second version

Revision ID: 3b204208185e
Revises: 
Create Date: 2022-07-07 13:03:22.617177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b204208185e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrap_registration_table',
    sa.Column('registration_id', sa.TEXT(), nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Address', sa.TEXT(), nullable=True),
    sa.Column('Correspondence_Address', sa.TEXT(), nullable=True),
    sa.Column('Validity', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('registration_id'),
    schema='scrap'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrap_registration_table', schema='scrap')
    # ### end Alembic commands ###
