"""1 version

Revision ID: 96e45b237542
Revises: 3b204208185e
Create Date: 2022-07-07 15:40:21.920807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e45b237542'
down_revision = '3b204208185e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrap_registration_table',
    sa.Column('Id', sa.INTEGER(), nullable=False),
    sa.Column('registration_id', sa.TEXT(), nullable=True),
    sa.Column('Name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('Address', sa.TEXT(), nullable=True),
    sa.Column('Correspondence_Address', sa.TEXT(), nullable=True),
    sa.Column('Validity', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    schema='scrap'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrap_registration_table', schema='scrap')
    # ### end Alembic commands ###
